// Code generated by protoc-gen-go.
// source: IOTRegistryStore.proto
// DO NOT EDIT!

/*
Package IOTRegistryStore is a generated protocol buffer package.

It is generated from these files:
	IOTRegistryStore.proto

It has these top-level messages:
	Registrant
	Alias
	Thing
	Spec
*/
package IOTRegistryStore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Registrant struct {
	RegistrantName   string `protobuf:"bytes,1,opt,name=RegistrantName" json:"RegistrantName,omitempty"`
	RegistrantPubkey []byte `protobuf:"bytes,3,opt,name=RegistrantPubkey,proto3" json:"RegistrantPubkey,omitempty"`
}

func (m *Registrant) Reset()         { *m = Registrant{} }
func (m *Registrant) String() string { return proto.CompactTextString(m) }
func (*Registrant) ProtoMessage()    {}

type Alias struct {
	Nonce []byte `protobuf:"bytes,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
}

func (m *Alias) Reset()         { *m = Alias{} }
func (m *Alias) String() string { return proto.CompactTextString(m) }
func (*Alias) ProtoMessage()    {}

type Thing struct {
	Alias            []string `protobuf:"bytes,1,rep,name=Alias" json:"Alias,omitempty"`
	RegistrantPubkey string   `protobuf:"bytes,2,opt,name=RegistrantPubkey" json:"RegistrantPubkey,omitempty"`
	Data             string   `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
	SpecName         string   `protobuf:"bytes,4,opt,name=SpecName" json:"SpecName,omitempty"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}

type Spec struct {
	RegistrantPubkey string `protobuf:"bytes,2,opt,name=RegistrantPubkey" json:"RegistrantPubkey,omitempty"`
	Data             string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *Spec) Reset()         { *m = Spec{} }
func (m *Spec) String() string { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()    {}
